# Generated by Django 5.0.6 on 2024-06-27 03:25

from django.db import migrations


def populate_privileges(apps, schema_editor):
    Privilege = apps.get_model('privileges', 'Privilege')
    Privilege.objects.create(name='Add Employee')
    Privilege.objects.create(name='Edit Employee')
    Privilege.objects.create(name='Delete Employee')


class Migration(migrations.Migration):

    dependencies = [
        ('privileges', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_privileges),
    ]
